# Generated by Django 4.1.5 on 2023-02-13 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_blacklist', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Обучается', 'Обучается'), ('Закончил', 'Закончил'), ('Прервал обучение', 'Прервал обучение')], default='Обучается', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('time_table', models.CharField(choices=[('Пн, Ср, Пт', 'Пн, Ср, Пт'), ('Вт, Чт, Сб', 'Вт, Чт, Сб')], default='Пн, Ср, Пт', max_length=255)),
                ('patent_number', models.CharField(max_length=255, unique=True)),
                ('patent_term', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
