# Generated by Django 4.1.5 on 2023-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetbyphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Обучается', 'Обучается'), ('Закончил', 'Закончил'), ('Прервал обучение', 'Прервал обучение')], max_length=255, null=True),
        ),
    ]
