# Generated by Django 4.1.5 on 2023-03-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='time_table',
        ),
    ]
