# Generated by Django 4.1.5 on 2023-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teacher_time_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обучается'), (2, 'Закончил'), (3, 'Прервал обучение')], default=1, max_length=255),
        ),
    ]
