# Generated by Django 4.1.5 on 2023-04-06 16:45
# Generated by Django 4.1.5 on 2023-04-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обучается'), (2, 'Закончил'), (3, 'Прервал обучение')], default=1),
        ),
    ]
