# Generated by Django 4.1.5 on 2023-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timetable',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Пн'), (1, 'Вт'), (1, 'Ср'), (1, 'Чт'), (1, 'Пт'), (1, 'Сб')], null=True),
        ),
    ]
