# Generated by Django 4.1.5 on 2023-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Обучается'), (2, 'Закончил'), (3, 'Прервал обучение')], null=True),
        ),
    ]
