# Generated by Django 4.1.5 on 2023-04-15 15:44

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timetable',
        ),
        migrations.AddField(
            model_name='user',
            name='end_work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Пн'), (2, 'Вт'), (3, 'Ср'), (4, 'Чт'), (5, 'Пт'), (6, 'Сб'), (7, 'Вс')], max_length=13, null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Клиент'), (1, 'Обучается'), (2, 'Закончил'), (3, 'Прервал обучение')], default=0),
        ),
    ]
