# Generated by Django 4.1.5 on 2023-04-15 16:33

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_timetable_user_end_work_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Пн'), ('2', 'Вт'), ('3', 'Ср'), ('4', 'Чт'), ('5', 'Пт'), ('6', 'Сб'), ('7', 'Вс')], max_length=13, null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
