# Generated by Django 4.1.5 on 2023-04-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_student_status'),
        ('users', '0013_alter_user_work_days'),
    ]

    operations = [
    ]
