# Generated by Django 4.1.5 on 2023-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20230417_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
