# Generated by Django 4.1.5 on 2023-03-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teacher_time_table'),
        ('applications', '0002_direction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('Маленькая', 'Маленькая'), ('Средняя', 'Средняя'), ('Большая', 'Большая')], max_length=50)),
                ('number_of_students', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timetable', models.CharField(choices=[('Пн, Ср, Пт', 'Пн, Ср, Пт'), ('Вт, Чт, Сб', 'Вт, Чт, Сб')], max_length=50, null=True)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.direction')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.groupstatus')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.teacher')),
                ('times', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.times')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('laptop', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Ждет звонка', max_length=50)),
                ('transaction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.direction')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.groups')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.payment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.source')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
