# Generated by Django 4.1.5 on 2023-03-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_groupstatus_payment_source_times_direction_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.groupstatus'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.times'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='timetable',
            field=models.CharField(blank=True, choices=[('Пн, Ср, Пт', 'Пн, Ср, Пт'), ('Вт, Чт, Сб', 'Вт, Чт, Сб')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='times',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
