# Generated by Django 4.1.5 on 2023-03-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_groups_end_date_alter_groups_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='client_request', max_length=50),
        ),
    ]
