# Generated by Django 4.1.5 on 2023-03-19 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 13, 23, 4, 86930, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 13, 23, 4, 87357, tzinfo=datetime.timezone.utc)),
        ),
    ]
