# Generated by Django 4.1.5 on 2023-03-19 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 13, 30, 7, 250449)),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 13, 30, 7, 250471)),
        ),
    ]
