# Generated by Django 4.1.5 on 2023-04-06 16:45
# Generated by Django 4.1.5 on 2023-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_status_alter_groups_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'client_request'), (2, 'sigh_trial_lesson'), (3, 'attend_trial_lesson')], default=1),
        ),
        migrations.AlterField(
            model_name='groups',
            name='audience',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Маленькая'), (2, 'Средняя'), (3, 'Большая')], default=1),
        ),
        migrations.AlterField(
            model_name='groups',
            name='timetable',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пн, Ср, Пт'), (2, 'Вт, Чт, Сб')], default=1),
        ),
    ]
