# Generated by Django 4.1.5 on 2023-04-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_status_historicalapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.payment'),
        ),
    ]
