# Generated by Django 4.1.5 on 2023-04-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_application_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.groups'),
        ),
    ]
