# Generated by Django 4.1.5 on 2023-04-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.groups'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.payment'),
        ),
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.rejectionreason'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.rejectionreason'),
        ),
    ]
