# Generated by Django 4.1.5 on 2023-04-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.groups'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.payment'),
        ),
    ]
