# Generated by Django 4.1.5 on 2023-04-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_groups_and_more'),
        ('applications', '0014_rejectionreason_alter_application_groups_and_more'),
    ]

    operations = [
    ]
