# Generated by Django 4.1.5 on 2023-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ждет звонка'), (2, 'Записался на пробный урок'), (3, 'Посетил пробный урок')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ждет звонка'), (2, 'Записался на пробный урок'), (3, 'Посетил пробный урок')], default=1, null=True),
        ),
    ]
