# Generated by Django 4.1.5 on 2023-04-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_application_reason_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='reason',
            new_name='rejection_reason',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='reason',
            new_name='rejection_reason',
        ),
    ]
