# Generated by Django 4.1.5 on 2023-04-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_application_status_and_more'),
        ('applications', '0017_rename_reason_application_rejection_reason_and_more'),
    ]

    operations = [
    ]
