# Generated by Django 4.1.5 on 2023-04-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_merge_20230420_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
