# Generated by Django 4.1.5 on 2023-04-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_remove_application_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='custom_id',
        ),
    ]
