# Generated by Django 4.1.5 on 2023-04-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_remove_application_custom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='note',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='note',
        ),
    ]
