# Generated by Django 5.0.6 on 2024-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_direction_color_rejectionreason_color_source_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ждет звонка'), (2, 'Записался на пробный урок'), (3, 'Посетил пробный урок'), (4, 'Неуспешная сделка')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ждет звонка'), (2, 'Записался на пробный урок'), (3, 'Посетил пробный урок'), (4, 'Неуспешная сделка')], default=1, null=True),
        ),
    ]
