image: python:3.11

stages:
  - deploy

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/backend/cms.backend && git pull $REPO dev && docker compose up -d --build && docker system prune -af"
  environment:
    name: production
    url: http://$SERVER_IP
  only:
    - dev
