version: '3.8'

services:

  postgres:
    image: postgres:13.0-alpine
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  django:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8019"
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8019:8019"
    env_file:
      - .env
    depends_on:
      - postgres
