version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn cms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOSTNAME: ${DB_HOST}
volumes:
  postgres_data:
  static_volume:
  media_volume: